contracts/core/Allo.sol, contracts/core/Registry.sol, contracts/core/interfaces/IAllo.sol, contracts/core/interfaces/IAllocationStrategy.sol, contracts/core/interfaces/IDistributionStrategy.sol, contracts/core/interfaces/IRegistry.sol, contracts/core/libraries/Metadata.sol, contracts/strategies/distribution/SplitPayouts.sol, docs/generated/contracts/core/Allo.md, docs/generated/contracts/core/interfaces/IAllo.md, docs/generated/contracts/core/interfaces/IDistributionStrategy.md, docs/generated/contracts/strategies/distribution/SplitPayoutsStrategy.md, test/foundry/Registry.t.sol
Sporadic updates from our call. These should all be good to merge. Will open an issue with next steps.
=> zach updates from call

.gitmodules, contracts/core/Registry.sol, test/foundry/core/Registry.t.sol
=> chore: move pendingOwner to mapping

contracts/strategies/allocation/alt-registry/mock/Registry.sol
Implements a simple registry proof of concept for the alt registry allocation
strategy
=> Mock Alt Registry

contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/direct-grants-simple/README.md, contracts/strategies/nft-winner/NFTVoteWinnerTakeAll.sol
=> Direct Grants Strategy Setup

contracts/core/Registry.sol, test/foundry/core/Registry.t.sol
=> Added missing Registry tests and fixed recoverFunds()

contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol
Fixes #128 
Fixes #129
Thanks @alphainfinitus
=> fix: addresses Issue 128/129

contracts/core/Allo.sol, contracts/core/IAllo.sol, test/foundry/core/Allo.t.sol
=> chore: rename approved -> cloneable"

contracts/DEPLOYMENTS.md, scripts/config/strategies.config.ts, scripts/strategies/deployStrategies.ts
=> deployed donation voting, deploy script fix, beautified DEPLOYMENTS.md

contracts/core/Registry.sol
This updates missed naming changes.
=> fix: naming update - identity - profile

contracts/strategies/donation-voting-custom-registry/DonationVotingCustomRegistryStrategy.sol, contracts/strategies/donation-voting-custom-registry/README.md, contracts/strategies/donation-voting-custom-registry/SimpleProjectRegistry.sol, contracts/strategies/donation-voting/DonationVotingStrategy.sol, test/foundry/strategies/DonationVotingCustomRegistryStrategy.t.sol, test/foundry/strategies/DonationVotingStrategy.t.sol
=> Donation Voting with Custom Registry

hardhat.config.ts
Add Celo alfajores and main networks
=> Add Celo Network

contracts/strategies/rfp-committee/RFPCommitteeStrategy.sol, contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPCommitteeStrategy.t.sol
=> chore: add tests for rfp-committee

contracts/strategies/qv-hackathon/HackathonQVStrategy.sol, test/foundry/strategies/HackathonQVStrategy.t.sol, test/foundry/strategies/QVBaseStrategy.t.sol, test/utils/MockEAS.sol
=> Hackathon qv tests

package.json, scripts/test/createPool.ts, scripts/test/createProfile.ts
=> chore: fix createProfile

contracts/core/Registry.sol, contracts/strategies/BaseStrategy.sol, contracts/strategies/IStrategy.sol, contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/donation-voting-custom-registry/DonationVotingCustomRegistryStrategy.sol, contracts/strategies/donation-voting-merkle-distribution/DonationVotingMerkleDistributionStrategy.sol, contracts/strategies/donation-voting/DonationVotingStrategy.sol, contracts/strategies/qv-base/QVBaseStrategy.sol, contracts/strategies/qv-governance/QVGovernanceERC20Votes.sol, contracts/strategies/qv-hackathon/HackathonQVStrategy.sol, contracts/strategies/qv-nft-tiered/QVNftTieredStrategy.sol, contracts/strategies/qv-simple/QVSimpleStrategy.sol, contracts/strategies/rfp-committee/RFPCommitteeStrategy.sol, contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, contracts/strategies/wrapped-voting-nftmint/NFT.sol, test/foundry/fuzz/QVSimpleStrategyFuzz.t.sol, test/foundry/strategies/BaseStrategy.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionStrategy.t.sol, test/foundry/strategies/HackathonQVStrategy.t.sol, test/foundry/strategies/QVBaseStrategy.t.sol, test/foundry/strategies/QVGovernanceERC20Votes.t.sol, test/foundry/strategies/QVNftTieredStrategy.t.sol, test/foundry/strategies/QVSimpleStrategy.t.sol, test/foundry/strategies/RFPCommitteeStrategy.t.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol, test/foundry/strategies/SimpleProjectRegistry.t.sol
=> Code review: public -> external, unused imports, poolId check

contracts/core/Registry.sol, contracts/core/interfaces/IRegistry.sol, test/foundry/core/Registry.t.sol
=> Registry: fix renaming issue

contracts/core/Allo.sol, contracts/core/Registry.sol, contracts/strategies/BaseStrategy.sol, contracts/strategies/wrapped-voting-nftmint/WrappedVotingNftMintStrategy.sol, scripts/config/registry.config.ts, scripts/core/deployAllo.ts, scripts/core/deployRegistry.ts, scripts/test/createProfile.ts, test/foundry/shared/RegistrySetup.sol
=> feat: make registry upgradable

contracts/strategies/BaseStrategy.md, contracts/strategies/BaseStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-vault/DonationVotingMerkleDistributionVaultStrategy.sol, test/utils/DonationVotingMerkleDistributionBaseMock.sol
- update strategy
- update readme 
fixes https://github.com/allo-protocol/allo-v2/issues/253
=> feat: add hooks to BaseStrategy

contracts/core/Allo.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-vault/DonationVotingMerkleDistributionVaultStrategy.sol
=> nonReentrant: Core contracts and strategies

.github/workflows/forge-test.yml, .gitignore, .gitmodules, .vscode/settings.json, contracts/strategies/BaseStrategy.sol, contracts/strategies/sablier-v2/LockupDynamicStrategy.sol, contracts/strategies/sablier-v2/LockupLinearStrategy.sol, contracts/strategies/sablier-v2/README.md, foundry.toml, remappings.txt, test/foundry/strategies/sablier-v2/LockupBase.t.sol, test/foundry/strategies/sablier-v2/LockupDynamicStrategy.t.sol, test/foundry/strategies/sablier-v2/LockupLinearStrategy.t.sol
Adds Sablier Strategies.
- Lockup Linear
- Lockup Dynamic
Would like to see 100% on test coverage when `yarn coverage:report` and `yarn coverage:html` are run.
=> feat/sablier strategies  (#139)

contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol
Changes done with grammatical or typing mistakes can be well seen in `file changed`.
Let's come down to gas optimizations then,
Much of the explanation is provided on this PR -> #237
Just want to add one more thing, `IRegistry private _registry` works like an address.
Here's a link explaining this -> https://ethereum.stackexchange.com/questions/112260/how-much-storage-is-required-to-store-an-interface
and if anyone seek more information on this particular change, this link will be helpful -> https://coinsbench.com/solidity-layout-and-access-of-storage-variables-simply-explained-1ce964d7c738
=> Update DirectGrantsSimpleStrategy.sol: Some gas optimizations and typos

contracts/strategies/donation-voting/DonationVotingStrategy.sol
=> Update DonationVotingStrategy.sol: Gas Optimization and errors fixed

contracts/core/interfaces/IStrategy.sol, contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/_poc/donation-voting-custom-registry/DonationVotingCustomRegistryStrategy.sol, contracts/strategies/_poc/donation-voting/DonationVotingStrategy.sol, contracts/strategies/_poc/proportional-payout/ProportionalPayoutStrategy.sol, contracts/strategies/_poc/qv-governance/QVGovernanceERC20Votes.sol, contracts/strategies/_poc/qv-hackathon/HackathonQVStrategy.sol, contracts/strategies/_poc/qv-nft-tiered/QVNftTieredStrategy.sol, contracts/strategies/_poc/sablier-v2/LockupDynamicStrategy.sol, contracts/strategies/_poc/sablier-v2/LockupLinearStrategy.sol, contracts/strategies/_poc/wrapped-voting-nftmint/WrappedVotingNftMintStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/qv-simple/QVSimpleStrategy.sol, contracts/strategies/rfp-committee/RFPCommitteeStrategy.sol, contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol, test/utils/MockStrategy.sol, test/utils/QVBaseStrategyTestMock.sol
- rfp: emit milestonCount on MilestoneSet event
- strategy: emit event on init
fixes #321 
fixes #322
=> chore: add function / event for spec indexing

contracts/strategies/_poc/qv-impact-stream/QVImpactStream.sol, contracts/strategies/_poc/qv-impact-stream/QVImpactStreamStrategy.sol, contracts/strategies/_poc/qv-impact-stream/README.md, test/foundry/strategies/QVImpactStreamStrategyTest.t.sol
=> Impact stream strategy

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPCommitteeStrategy.t.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/245
=> fix: add recipientAddress in register for RFP

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/458
=> fix: add onlyPoolManager modifier to RFP setPoolActive

contracts/strategies/_poc/donation-voting/DonationVotingStrategy.sol, contracts/strategies/_poc/proportional-payout/ProportionalPayoutStrategy.sol, contracts/strategies/_poc/wrapped-voting-nftmint/WrappedVotingNftMintStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/qv-base/QVBaseStrategy.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/839
=> fix: update _checkOnlyAfterAllocation logic

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/176
=> fix: delete existing milestone on reset

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/497
=> fix: prevent front-running of proposalBid

contracts/strategies/qv-base/QVBaseStrategy.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/150
=> fix: ensure allocator used credits are accounted

contracts/strategies/qv-base/QVBaseStrategy.sol
Refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/48
=> fix: ensure votes are accounted for in qv

contracts/core/Anchor.sol, contracts/core/Registry.sol, test/foundry/core/Anchor.t.sol, test/foundry/core/Registry.t.sol
https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/380
=> fix: anchor creation

contracts/strategies/qv-base/QVBaseStrategy.sol, test/foundry/strategies/QVBaseStrategy.t.sol
https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/589
=> fix: review threshold, add test

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/199
=> fix:  start recipientsCounter at 1

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/569
=> added recipient counter reference

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
Refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/492
=> fix: update _distribute to ensure milestone can be distributed

contracts/strategies/qv-base/QVBaseStrategy.sol, test/foundry/strategies/QVBaseStrategy.t.sol
Refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/729
Refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/699
=> fix: update review status

contracts/core/Allo.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/752
=> fix: fix the fee deduction logic

contracts/core/Allo.sol, contracts/core/Registry.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/852
=> fix: make sure to use upgradeable access control

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/846
=> fix: milestone amount cannot be 0

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol, test/foundry/strategies/RFPSimpleStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/510
=> fix: allow distributing only pending milestones

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/723
=> fix: ensure distribute cannot happen without merkleRoot

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/170
=> fix: ensure metadata is tracked in RFP

contracts/core/Anchor.sol, test/foundry/core/Anchor.t.sol
refs: https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/883
=> add ERC721- and ERC1155 Holder

contracts/core/Allo.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/20
=> fix: pass msg.value in registerRecipient

contracts/core/Allo.sol, test/foundry/core/Allo.t.sol
refs: https://github.com/allo-protocol/allo-v2/pull/377/files
=> added msg.value check

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/qv-base/QVBaseStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol, test/foundry/strategies/QVBaseStrategy.t.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/579
=> chore: ensure review can be done during allocation

contracts/core/Registry.sol, test/foundry/shared/Accounts.sol, test/foundry/shared/RegistrySetup.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol, test/utils/TestUtilities.sol
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/862
=> deploy anchor using

contracts/strategies/_poc/donation-voting/DonationVotingStrategy.sol, test/foundry/strategies/DonationVotingStrategy.t.sol, test/utils/Permit2Mock.sol, test/utils/TestUtilities.sol
=> bug: fix poc to ensure funds are sent to vault

contracts/strategies/qv-base/QVBaseStrategy.sol
- https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/589
- https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/729
=> chore: fix review status

contracts/strategies/_poc/micro-grants/MicroGrantsGovStrategy.sol
=> removed try catch

contracts/strategies/_poc/micro-grants/MicroGrantsGovStrategy.sol
Reverts allo-protocol/allo-v2#431
=> Revert "removed try catch"

contracts/strategies/_poc/direct-grants-simple/README.md, docs/DEPLOY_CHECKLIST.md, scripts/config/allo.config.ts
=> docs: fix several typo issues

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol
This change makes it 100x easier to create the registration data in our sdk
=> change order of register params

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol
related to this commit #442 
No problem on the contract itself, but just felt complicated when I used this strategy.
=> fixed order _registerRecipient func

contracts/strategies/_poc/sqf-superfluid/SQFSuperFluidStrategy.sol
=> changed distribution flag

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol
closes https://github.com/gitcoinco/grants-stack/issues/2961
=> add registration start/end time to direct grants strategy

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol
* add registration start/end time to direct grants strategy
* direct grant strategy: revert registration if registration is not active
=> add registration start/end time to direct grants strategy (#478)

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-vault/DonationVotingMerkleDistributionVaultStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
closes https://github.com/gitcoinco/grants-stack/issues/2960
=> QF strategy registrationStartTime can be in the past to allow timestamps to be changed at any time

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-base/IDAI.sol, contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-vault/DonationVotingMerkleDistributionVaultStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionDirectTransferStrategy.t.sol, test/utils/PermitSigUtilsDAI.sol
closes https://github.com/gitcoinco/grants-stack/issues/2959
=> implement QF donation with the DAI permit

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
fixes https://github.com/allo-protocol/allo-v2/issues/485
=> audit: use ++i in place of i++

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: Redundant milestone existence check

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: 3.4.3 setPoolActive emits the PoolActive event twice per call

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: Typos, misleading and inaccurate comments

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: Off-by-one errors in validating _milestoneId is a valid milestone

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: TODOs in code

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
fixes https://github.com/allo-protocol/allo-v2/issues/502
=> audit: Unused state variable

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol
=> audit: Section containing structs is incorrectly labelled as Storage

contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol
=> audit: fix _sender in allowance check

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
=> audit: Transfer without permit

contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol
=> audit: fix signature length

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol
fixes https://github.com/allo-protocol/allo-v2/issues/509
=> audit: Recipients cannot be marked as InReview and then reaccepted

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol
fixes https://github.com/allo-protocol/allo-v2/issues/487
=> audit: save a storage slot by packing timestamps

contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol
=> audit: Recipients can frontrun reviewSetMilestones

contracts/core/libraries/Errors.sol, contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol, contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol, test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol
Note: [2f5b249](https://github.com/allo-protocol/allo-v2/pull/516/commits/2f5b249d0b0320ec8fd4a9e2af77b9ee8af318b9) is added as a product requirement and is included in this PR
fixes https://github.com/allo-protocol/allo-v2/issues/484
=> Audit fixes

.openzeppelin/unknown-314159.json, reports/deployment-logs/core/deploy.log, reports/deployment-logs/core/deployAllo/filecoin-calibration/20240412_195124/deploy-20240412_195124.log, reports/deployment-logs/core/deployAllo/filecoin-calibration/20240412_203640/deploy-20240412_203640.log, reports/deployment-logs/core/deployContractFactory/filecoin-calibration/20240412_233154/deploy-20240412_233154.log, reports/deployment-logs/core/deployRegistry/filecoin-calibration/20240412_102206/deploy-20240412_102206.log, scripts/core/deployAllNetworks.sh, scripts/deployments/allo.deployment.json, scripts/deployments/contractFactory.deployment.json, scripts/deployments/registry.deployment.json
Deploy core contracts on filecoin testnet
=> filecoin init

.openzeppelin/kovan.json, reports/deployment-logs/core/deploy.log, reports/deployment-logs/core/deployAllo/lukso-mainnet/20240419_172024/deploy-20240419_172024.log, reports/deployment-logs/core/deployContractFactory/lukso-mainnet/20240419_172348/deploy-20240419_172348.log, reports/deployment-logs/core/deployRegistry/lukso-mainnet/20240419_171518/deploy-20240419_171518.log, reports/deployment-logs/strategies/deployDirectGrants/lukso-mainnet/20240419_172709/deploy-20240419_172709.log, reports/deployment-logs/strategies/deployDonationVotingMerkleDistributionDirect/lukso-mainnet/20240419_181832/deploy-20240419_181832.log, scripts/config/common.config.ts, scripts/core/deployAllNetworks.sh, scripts/deployments/allo.deployment.json, scripts/deployments/contractFactory.deployment.json, scripts/deployments/directgrantssimplestrategy.deployment.json, scripts/deployments/donationvotingmerkledistributiondirecttransferstrategy.deployment.json, scripts/deployments/registry.deployment.json
Note: The .openzepplin file gets generated as .kovan which is weird. 
Not editing cause we can't rename the file.
=> chore: add lukso mainnet

contracts/strategies/direct-grants-lite/DirectGrantsLite.sol
=> fix: prevent sending native on register

contracts/strategies/direct-grants-lite/DirectGrantsLite.sol
=> fix: ensure only Allo can deposit native

contracts/strategies/direct-grants-lite/DirectGrantsLite.sol
=> fix: unchecked loop operator

contracts/strategies/direct-grants-lite/DirectGrantsLite.sol
=> fix: typos/comments

contracts/strategies/direct-allocation/DirectAllocation.sol, package.json, reports/deployment-logs/core/deploy.log, reports/deployment-logs/strategies/deployDirectAllocation/sepolia/20240711_092006/deploy-20240711_092006.log, reports/deployment-logs/strategies/deployDirectAllocation/sepolia/20240716_101849/deploy-20240716_101849.log, reports/deployment-logs/strategies/deployDirectAllocation/sepolia/20240716_102132/deploy-20240716_102132.log, reports/deployment-logs/strategies/deployDirectAllocation/sepolia/20240716_102240/deploy-20240716_102240.log, scripts/config/strategies.config.ts, scripts/core/deployAllNetworks.sh, scripts/deployments/directallocationstrategy.deployment.json, scripts/strategies/deployDirectAllocation.ts, scripts/test/createDirectAllocationPool.ts, scripts/test/createPool.ts, test/foundry/strategies/DirectAllocation.t.sol
Strategy Deployed at : 0x56662F9c0174cD6ae14b214fC52Bd6Eb6B6eA602
Pool Created at: 386
closes [BLU-73](https://linear.app/gitcoin/issue/BLU-73/review-direct-donation-contract)
closes [BLU-74](https://linear.app/gitcoin/issue/BLU-74/deploy-strategy-on-sepolia)
=> Direct allocation

contracts/core/libraries/QFHelper.sol, test/foundry/core/QFHelper.t.sol, test/utils/MockQFHelper.sol
Closes #609 
Quadratic Funding Library that can be used by different strategies to handle voting and calculating the matching amount.
=> feat: QF helper library

.openzeppelin/unknown-1088.json, hardhat.config.ts, reports/deployment-logs/core/deploy.log, reports/deployment-logs/core/deployAllo/metisAndromeda/20240729_143733/deploy-20240729_143733.log, reports/deployment-logs/core/deployContractFactory/metisAndromeda/20240729_143511/deploy-20240729_143511.log, reports/deployment-logs/core/deployRegistry/metis/20240729_142656/deploy-20240729_142656.log, reports/deployment-logs/core/deployRegistry/metis/20240729_143105/deploy-20240729_143105.log, reports/deployment-logs/core/deployRegistry/metisAndromeda/20240729_143120/deploy-20240729_143120.log, reports/deployment-logs/core/deployRegistry/metisAndromeda/20240729_143157/deploy-20240729_143157.log, reports/deployment-logs/strategies/deployDirectAllocation/metisAndromeda/20240729_144147/deploy-20240729_144147.log, reports/deployment-logs/strategies/deployDirectGrantsLite/metisAndromeda/20240729_144147/deploy-20240729_144147.log, reports/deployment-logs/strategies/deployDonationVotingMerkleDistributionDirect/metisAndromeda/20240729_144147/deploy-20240729_144147.log, scripts/config/allo.config.ts, scripts/config/common.config.ts, scripts/config/registry.config.ts, scripts/config/strategies.config.ts, scripts/core/deployAllNetworks.sh, scripts/deployments/allo.deployment.json, scripts/deployments/contractFactory.deployment.json, scripts/deployments/directallocationstrategy.deployment.json, scripts/deployments/directgrantslitestrategy.deployment.json, scripts/deployments/donationvotingmerkledistributiondirecttransferstrategy.deployment.json, scripts/deployments/registry.deployment.json, scripts/strategies/deployDirectAllocation.ts, scripts/strategies/deployDirectGrantsLite.ts, scripts/strategies/deployDonationVotingMerkleDistributionDirect.ts, scripts/test/createDirectAllocationPool.ts
=> feat: add metis network

contracts/core/Allo.sol, contracts/core/interfaces/IAllo.sol, test/foundry/core/Allo.t.sol
=> feat: add function to add/remove multiple managers from multiple pools

contracts/strategies/EasyRPGF.sol, test/foundry/integration/EasyRPGF.t.sol
=> feat: refactor EasyRPGF strategy

contracts/core/Allo.sol, contracts/core/interfaces/IAllo.sol, foundry.toml, test/foundry/core/Allo.t.sol, test/foundry/strategies/BaseStrategy.t.sol, test/foundry/strategies/DirectGrantsLite.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionDirectTransferStrategy.t.sol, test/foundry/strategies/DonationVotingMerkleDistributionVaultStrategy.t.sol, test/foundry/strategies/MicroGrantsBaseStrategy.t.sol, test/foundry/strategies/MicroGrantsGovStrategy.t.sol, test/foundry/strategies/MicroGrantsHatsStrategy.t.sol, test/foundry/strategies/MicroGrantsStrategy.t.sol, test/foundry/strategies/ProportionalPayoutStrategy.t.sol, test/foundry/strategies/QVImpactStreamStrategyTest.t.sol, test/foundry/strategies/SQFSuperFluidStrategy.t.sol, test/foundry/strategies/WrappedVotingNftMintStrategy.t.sol, test/foundry/strategies/sablier-v2/LockupDynamicStrategy.t.sol, test/foundry/strategies/sablier-v2/LockupLinearStrategy.t.sol, test/utils/MockStrategy.sol
=> feat: update Allo to comply new CoreBaseStrategy.sol

contracts/core/Allo.sol, contracts/strategies/_poc/direct-grants-simple/DirectGrantsSimpleStrategy.sol, foundry.toml, test/foundry/integration/Allo.t.sol, test/foundry/integration/DirectAllocation.t.sol, test/foundry/integration/DonationVotingOffchain.t.sol, test/foundry/integration/DonationVotingOnchain.t.sol, test/foundry/integration/EasyRPGF.t.sol, test/foundry/integration/IBiconomyForwarder.sol, test/foundry/integration/IOwnable.sol, test/foundry/integration/ITransparentUpgradeableProxy.sol, test/foundry/integration/IntegrationBase.sol, test/foundry/integration/QVSimple.t.sol, test/foundry/integration/RFPSimple.t.sol
=> test: refactor integration tests for Allo.sol and add missing tests

contracts/strategies/QVImpactStream.sol, contracts/strategies/QVSimple.sol, test/foundry/integration/QVImpactStream.t.sol, test/foundry/strategies/QVImpactStream.t.sol, test/foundry/strategies/QVImpactStream.tree
QVImpactStream strategy refactor leveraging the new strategies and tools.
=> feat: qv impact stream refactor

contracts/core/interfaces/IBaseStrategy.sol, contracts/strategies/CoreBaseStrategy.sol, test/foundry/strategies/CoreBaseStrategy.t.sol
Makes sure that the poolAmount is not reduced. PoolManager can withdraw non-pool tokens or excessive pool tokens.
=> fix: withdraw

contracts/strategies/_poc/easy-rf/EasyRetroFundingStrategy.sol
Description: Do not allow round date updates after the distribution phase  has started
=> fix: retrofunding strategy
