allo-protocol/allo-v2

contracts/core/Allo.sol
contracts/strategies/BaseStrategy.sol

`private` variables can't be read by contracts that inherit them. I removed that from BaseStrategy so strategies can access these variables.
Also changed `initialize()` to public from external so strategies can call `super.initialize()`.

Foundation fixes

---

contracts/strategies/README.md

This pull request adds a detailed README.md file for the strategy folder. The README provides comprehensive specifications and guidelines for documenting each strategy within the folder. 
It includes sections covering an overview, recipient eligibility logic, register recipient logic, allocator eligibility logic, allocation logic, distribution logic, and additional developer specifications. 
The README offers a structured format with specific questions to answer for each section, ensuring all necessary information is included. Developers can follow these guidelines to document the strategy's functionality, logic, and usage effectively.

General README for strategy specs

---

test/foundry/core/Registry.t.sol
test/foundry/shared/Accounts.sol
test/foundry/shared/AlloSetup.sol
test/foundry/shared/RegistrySetup.sol
test/foundry/strategies/QVSimpleStrategy.t.sol

This pull request introduces a set of shared Solidity files for testing.
Now, rather than configuring `Allo` and the `Registry` with multiple accounts in each strategy test file, we can effortlessly import these shared contracts and invoke the init functions and everything is set up.
Also I added predefined accounts that can be directly utilized without the need to create new addresses in any test file.

Added shared test files

---

contracts/core/Anchor.sol
contracts/core/Registry.sol
test/foundry/core/Anchor.t.sol
test/foundry/core/Registry.t.sol
test/foundry/utils/TestUtilities.sol

Here's a simple implementation of the Anchor.
A few important things to note:
- This should be deployed once and then clones should be put in front of it for each individual deployment.
- Clones should be created with CREATE2 to ensure they can be consistent across chains.
- Clones should use `keccak256(name)` as the salt, so that if an identity changes their name, they get a new anchor address.
- The logic in Registry.sol needs to change so that users remain owners of identities, even after they change the name.

Minimal Anchor Address Implementation

---

contracts/strategies/wrapped-voting-nftmint/NFT.sol
contracts/strategies/wrapped-voting-nftmint/NFTFactory.sol
contracts/strategies/wrapped-voting-nftmint/WrappedVotingNftMintStrategy.sol
test/foundry/shared/EventSetup.sol
test/foundry/strategies/DonationVotingStrategy.t.sol
test/foundry/strategies/ProportionalPayoutStrategy.t.sol
test/foundry/strategies/WrappedVotingNftMintStrategy.t.sol
test/utils/MockRevertingReceiver.sol

fixes #148 
Add tests for Wrapped NFT strategy
Need eyes on:
`test_nftContractCreated` & `test_getRecipientStatus`
```typescript
function getRecipientStatus(address _recipientId) external view override returns (RecipientStatus) {
return nftFactory.isNFTContract(_recipientId) ? RecipientStatus.Accepted : RecipientStatus.None;
}
```
Question: why the `recipientId` and not the NFT contract address here?

Wrapped tests

---

contracts/strategies/donation-voting-custom-registry/SimpleProjectRegistry.sol
contracts/strategies/wrapped-voting-nftmint/NFT.sol

We used Ownable.sol and NFT.sol from different libraries, which caused the abi exporter not to work.
This PR fixes the problem.

fix imports

---

contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol
test/foundry/strategies/DirectGrantsSimpleStrategy.t.sol

The milestone flow is now updated to 
- recipient registers (no changes here)
- pool manager reviews the recipient (no changes here)
- recipient sets milestones (by invoking setMilestones, which can be invoked multiple times until approved)
- pool manager approves milestones (this will be a new function)
- pool manager can also invoke setMilestones to set milestones and approve them
fixes #214 
fixes #227

chore: update milestone logic

---

contracts/strategies/rfp-simple/RFPSimpleStrategy.sol

Here's the explanation of why I changed the order of those particular state variables:
Usually, EVM stores state variables or storage variables in slots, each slot upto 32 bytes of data and these slots are directly related to gas, i.e more the slots, more the gas gonna be used up!!
So if by anyway we reduced the number of slots, we might optimize the gas a little bit. Take a look at this:
Just for some information sake:
- Address takes up 20 bytes
- bool takes up 1 byte
- uint256 takes up 32 bytes and covers up the whole storage
and here's my implementation:
Saving 1 extra slot, Hope that makes you clear!!
Plus there's some grammatical fixes in the comments, just some extra stuff done...

Update RFPSimpleStrategy.sol: Enhanced Gas Optimizations and fixed some errors in comments

---

contracts/strategies/donation-voting-merkle-distribution/DonationVotingMerkleDistributionStrategy.md
contracts/strategies/donation-voting-merkle-distribution/DonationVotingMerkleDistributionStrategy.sol
contracts/strategies/donation-voting/DonationVotingStrategy.sol
contracts/strategies/qv-base/QVBaseStrategy.sol
contracts/strategies/wrapped-voting-nftmint/WrappedVotingNftMintStrategy.sol
test/foundry/fuzz/QVSimpleStrategyFuzz.t.sol
test/foundry/shared/EventSetup.sol
test/foundry/strategies/DonationVotingMerkleDistributionStrategy.t.sol
test/foundry/strategies/DonationVotingStrategy.t.sol

* Updates recipient metadata via `registerRecipient`
* Checks if the recipient's internal status is "Rejected.", then update internal status to "Appealed."
* Checks if the recipient's internal status is "Accepted.", then update internal status to "Pending."
* Checks if the recipient's internal status is "Pending"/"Appealed", no change in status.
* Emits `UpdatedRegistration` event.
fixes #246

chore: handle re-registration

---

contracts/core/Allo.sol

The changes I made are:
`uint256 i = 0;` -> `uint256 i;`
Why to waste gas for just initializing any variable to 0 even after we know that default value of all `uint` and `int` is 0..
There's one more thing I would love to point out, see one of the code snippets from this file:
```
for (uint256 i = 0; i < numPools;) {
_allocate(_poolIds[i], _datas[i]);
unchecked {
i++;
}
}
```
Must say, that `unchecked` part is really worth of appreciation and the idea behind it. But what if we make `i++` -> `++i`.
if that `i` won't be used anywhere after this loop, it be safe to use `++i` and will save even more gas. Even I first thought that what will even happen after making this kind of change, but after running a demo code in remix...it was effective.
I haven't made this change yet, that's why pointed …

Update Allo.sol: Optimized code

---

contracts/core/Registry.sol
test/foundry/core/Registry.t.sol

This enables 
- creating profiles on behalf of other users
- restrict member creation to only profile owner and not creator of profile 
fixes: https://github.com/allo-protocol/allo-v2/issues/327
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/7
This would enable GiveEth to optionally create profiles on behalf of the profile owner but will hold no ownership of the profile

chore: profileId is generated using owner

---

contracts/core/Registry.sol
test/foundry/core/Registry.t.sol

This enables 
- creating profiles on behalf of other users
- restrict member creation to only profile owner and not creator of profile 
fixes: https://github.com/allo-protocol/allo-v2/issues/327
refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/7
This would enable GiveEth to optionally create profiles on behalf of the profile owner but will hold no ownership of the profile

fix: profileId is generated using owner #326

---

contracts/strategies/_poc/qv-hackathon/SchemaResolver.sol
contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol
contracts/strategies/qv-base/QVBaseStrategy.sol
test/foundry/strategies/HackathonQVStrategy.t.sol
test/foundry/strategies/QVBaseStrategy.t.sol
test/foundry/strategies/QVGovernanceERC20Votes.t.sol
test/foundry/strategies/QVNftTieredStrategy.t.sol
test/foundry/strategies/QVSimpleStrategy.t.sol

refs https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/256

fix: add recieve function

---

contracts/strategies/_poc/qv-impact-stream/QVImpactStreamStrategy.sol
test/foundry/strategies/QVImpactStreamStrategyTest.t.sol

Removing this check for Impact Stream Strategy -->
```solidity
[438] if (isUsingRegistryAnchor && !_isProfileMember(recipientId, recipientAddress)) revert UNAUTHORIZED();
```
@0xKurt and I deployed this new version to run the scripts from on Goerli.
cc: @0xKurt @thelostone-mc

Remove check on register recipient

---

test/foundry/shared/Accounts.sol

It has a typo, "adresses". Fixed to "addresses".

Typo Accounts.sol comment

---

contracts/strategies/_poc/sqf-superfluid/SQFSuperFluidStrategy.sol
test/foundry/strategies/SQFSuperFluidStrategy.t.sol

The total amount of units in the GDA pool needs to be lower than the flow rate being distributed for the matching pool to send funds to the recipients.
Because in the calculation the amount of units in the GDA pool grows with the allocation flow rate they can easily reach that limit.
An underflow in `adjustWeightings()` happens when the only allocator closes the stream two times, because this happens in the SuperApp termination callback the SuperApp gets jailed by the Superfluid Host contract.
This fixes the issues by:
- Scaling down the flow rate in `adjustWeightings()` for units calculation purpose to make sure the units are order of magnitudes lower than the distribution flow rate for pools and donations of realistic sizes.
- Using a formula that guarantees a positive number for the …

fix units calculation in SQFSuperFluidStrategy

---

contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol
contracts/strategies/_poc/sqf-superfluid/SQFSuperFluidStrategy.sol
test/foundry/strategies/SQFSuperFluidStrategy.t.sol

Adds two emergency functions to the recipient Super Apps in the SQF Superfluid strategy to allow recipients to withdraw funds and close incoming streams.
Creates a factory to deploy the recipient Super Apps since the above change put the contract size over the deploy limit.
Also makes the Super App registration key configurable upon deployment to support deploying to mainnet.

SQF: Emergency Functions, Super App factory

---

contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol
test/foundry/strategies/SQFSuperFluidStrategy.t.sol

Adding to https://github.com/allo-protocol/allo-v2/pull/474
Deploying on mainnet requires the factory to call `registerApp` and not the Super App.

fix: RecipientSuperAppFactory should register app

---

contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol
test/foundry/strategies/DonationVotingMerkleDistributionBase.t.sol

This is not part of the audit but we wanted to emit the tx.origin on allocation as well

chore: emit tx.origin in Allocated

---

contracts/strategies/_poc/qv-impact-stream/QVImpactStreamStrategy.sol
contracts/strategies/_poc/qv-impact-stream/README.md
test/foundry/strategies/QVImpactStreamStrategyTest.t.sol

- Refactors `QVImpactStreamStrategy` to inherit from `QVBaseStrategy`
- fixes unit tests
Regarding integration tests, I think we should first focus on `Allo` and then we can come back to creating integration tests for strategies (maybe for our most refined ones like qv/direct grants). I created this issue and put it in the backlog for now https://github.com/allo-protocol/allo-v2/issues/599
Closes https://github.com/allo-protocol/allo-v2/issues/595

refactor: qv impact stream strategy

---

contracts/core/Allo.sol
contracts/core/interfaces/IAllo.sol
test/foundry/core/Allo.t.sol
test/foundry/integration/Allo.t.sol
test/foundry/integration/IBiconomyForwarder.sol
test/foundry/shared/Accounts.sol
test/foundry/shared/AlloSetup.sol
test/utils/MockAllo.sol

feat: implement erc2771

---

contracts/extensions/contracts/RecipientsExtension.sol
contracts/extensions/interfaces/IRecipientsExtension.sol
contracts/strategies/RFPSimple.sol
foundry.toml
test/foundry/extensions/RecipientsExtension.t.sol
test/foundry/integration/RFPSimple.t.sol
test/utils/MockStrategyRecipientsExtension.sol

The idea of these changes is that:
- It should be easy to add custom review logic to each new Status being set in `reviewRecipients()` (e.g. do sth on Status.Reject).
- It should be easy to differentiate a new Status from an old Status. Currently in `reviewRecipients()` it is not straight forward to see which statuses are new and which are not, because a row with 64 statuses is passed as param and set to storage directly.
- It should be possible and easy to access the recipient id of the new Status being set.
- It should be easy to override `reviewRecipients()` to use a different permission logic.
- We should keep the gas optimization of using a bitmap for recipients statuses.
Some ideas implemented so far:

feat: make reviewRecipients more customizable
